org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=false
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false
kotlin.stdlib.default.dependency=false
kotlinx.atomicfu.enableNativeIrTransformation=true

carrierRepository=https://github.com/botiverse/KuiklyBase-components.git
kotlinVersion=2.0.21-KBA-010
atomicfuBuildPluginVersion=0.23.2
atomicfuVersion=0.23.2-raft.1
atomicfuUpstreamRepository=https://github.com/Kotlin/kotlinx.atomicfu.git
atomicfuUpstreamSha=7e640bab1db140a398f735be97e3f07f97019ac0
atomicfuPatchSha256=71690f6bb553cd0741ba0132711aa576e73fb9e02b3a0600e02f8676c6d50f70
coroutinesVersion=1.8.0-raft.1
coroutinesUpstreamRepository=https://github.com/Kotlin/kotlinx.coroutines.git
coroutinesUpstreamSha=8c516f5ab1fcc39629d2838489598135eedd7b80
coroutinesPatchSha256=b85b83e2a3237fee2a5e593ad72baade99c6e1f3bb9f6130122ff9fbd42b2636
