# source 'https://cdn.cocoapods.org'
source "https://git.woa.com/TencentVideoShared/VideoBase.git"
source "https://git.woa.com/TencentVideoShared/VideoBase-snapshot.git"
source "https://mirrors.tencent.com/repository/generic/pod-go/T-CocoaPods/Specs/"

target 'iosApp' do
  use_frameworks!
  platform :ios, '12.0'
#   pod 'network', :path => '../network/build/cocoapods/publish/debug'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings["ARCHS[sdk=iphonesimulator*]"] = "x86_64"  # 模拟器使用x86_64,M1电脑就可以用模拟器了
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Tencent"
end
